
import { MenuSection } from './types';

export const MENU_DATA: MenuSection[] = [
  {
    id: 'pizza',
    title: 'البيتزا الإيطالي',
    emoji: '🍕',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=60&w=800',
    subtitles: ['وسط', 'كبير'],
    items: [
      { name: 'مارجريتا', prices: ['70', '80'] },
      { name: 'خضروات', prices: ['70', '80'] },
      { name: 'بانيه قطع', prices: ['70', '80'] },
      { name: 'مشروم', prices: ['80', '90'] },
      { name: 'سلامي', prices: ['80', '100'] },
      { name: 'عشاق الجبنة', prices: ['80', '100'], isPopular: true },
      { name: 'لحمة مفرومة', prices: ['80', '100'] },
      { name: 'سجق شرقي', prices: ['80', '100'] },
      { name: 'سوسيس (هوت دوج)', prices: ['80', '100'] },
      { name: 'تونا', prices: ['100', '110'] },
      { name: 'بسطرمة', prices: ['100', '110'] },
      { name: 'شاورما فراخ', prices: ['100', '120'], isPopular: true },
      { name: 'شاورما لحمة', prices: ['100', '120'] },
      { name: 'شيش طاووق', prices: ['100', '120'] },
      { name: 'فاهيتا ميكسيكان', prices: ['100', '120'], isSpicy: true },
      { name: 'تشيكن رانش', prices: ['110', '130'], isPopular: true },
      { name: 'تشيكن باربيكيو', prices: ['110', '130'] },
      { name: 'تشيكن فاير', prices: ['110', '130'], isSpicy: true },
      { name: 'تشيكن تايجر', prices: ['110', '130'] },
      { name: 'تشيكن ليدن', prices: ['120', '140'] },
      { name: 'زنجر سوبريم', prices: ['120', '140'], isSpicy: true },
      { name: 'ميكس لحوم', prices: ['120', '140'] },
      { name: 'كريزي تشيكن (فراخ + مشروم)', prices: ['140', '120'] },
      { name: 'ميكس فراخ', prices: ['130', '150'], isPopular: true },
      { name: 'جمبري', prices: ['140', '150'] },
      { name: 'سوبريم فراخ', prices: ['140', '150'] },
      { name: 'فواكة البحر', prices: ['140', '150'] },
      { name: 'تشكن سبايسي (فراخ+مشروم+زنجر+سبايسي)', prices: ['-', '150'], isSpicy: true },
    ]
  },
  {
    id: 'crepes',
    title: 'الكريب Crep',
    emoji: '🌯',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?q=60&w=800',
    items: [
      { name: 'بانية بارد', prices: ['45'] },
      { name: 'كرسبي بانية حار', prices: ['45'], isSpicy: true },
      { name: 'كريب شوكولاتة', prices: ['50'] },
      { name: 'بطاطسيكو (بانيه + بطاطس)', prices: ['50'] },
      { name: 'سوبر كرانش (بانيه + رومي مدخن)', prices: ['50'], isPopular: true },
      { name: 'كفتة مشوية', prices: ['50'] },
      { name: 'كبدة إسكندراني', prices: ['50'] },
      { name: 'برجر لحمة', prices: ['50'] },
      { name: 'تشيكن برجر', prices: ['50'] },
      { name: 'هوت دوج (سوسيس)', prices: ['50'] },
      { name: 'ميكس جبن (موتزاريلا+رومي+جبنة شيدر+فلفل+طماطم+زيتون)', prices: ['50'] },
      { name: 'شاورما فراخ', prices: ['70'], isPopular: true },
      { name: 'شاورما لحمة', prices: ['70'] },
      { name: 'شيش طاووق', prices: ['70'] },
      { name: 'برجر تكساس', prices: ['70'] },
      { name: 'زنجر سوبريم', prices: ['75'], isSpicy: true },
      { name: 'تشيكن بسنت', prices: ['75'] },
      { name: 'F16 (زنجر + بطاطس + صوص شيدر)', prices: ['85'], isSpicy: true },
      { name: '122 (زنجر+بطاطس+صوص شيدر+صوص الخاص)', prices: ['85'], isPopular: true },
      { name: 'إيطاليانو (زنجر + رومي مدخن + باربيكيو)', prices: ['85'] },
      { name: 'فاهيتا ميكسيكان (فراخ + مشروم + باربيكيو)', prices: ['85'], isSpicy: true },
      { name: 'فاهيتا لحمة (لحمة + مشروم + باربيكيو)', prices: ['85'] },
      { name: 'ميكس لحمة (كفتة + برجر + هوت دوج)', prices: ['85'] },
      { name: 'ميكس تربو (كفتة + برجر + هوت دوج + مشروم)', prices: ['85'] },
      { name: 'ديناميت (كفتة + برجر + هوت دوج + سجق)', prices: ['85'] },
      { name: 'تشيكن لارج (زنجر + شيش + رومي)', prices: ['85'] },
      { name: 'تشيكن رويال (زنجر + شيش + بطاطس)', prices: ['85'] },
      { name: 'عمار (زنجر + شيش + بانية)', prices: ['85'] },
      { name: 'ميكس فراخ (فراخ + بانية + زنجر + صوص الخاص)', prices: ['85'], isPopular: true },
      { name: 'سبايسي (مشروم + بانية + زنجر + باربيكيو)', prices: ['85'], isSpicy: true },
      { name: 'حركات (كرسبي + بانية + زنجر + بطاطس)', prices: ['85'] },
      { name: 'جانجو (هوت دوج + بانية + شيش)', prices: ['85'] },
      { name: 'جولد ميكس (هوت دوج + زنجر + جبنة فرنسية + صوص تايجر)', prices: ['85'] },
      { name: 'ميكس شاورمة (شاورمة فراخ + شاورمة لحمة)', prices: ['90'] },
      { name: 'جمبري', prices: ['90'] },
      { name: 'سوبر فياجرا (جمبري + كابوريا + كلماري)', prices: ['100'] },
    ]
  },
  {
    id: 'sandwiches',
    title: 'سندوتشات & برجر',
    emoji: '🥪',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=60&w=800',
    items: [
      { name: 'تشيز برجر ماكدونالدز جامبو', prices: ['40'], isPopular: true },
      { name: 'برجر لحمة', prices: ['20'] },
      { name: 'تشيز برجر', prices: ['25'] },
      { name: 'برجر بيض', prices: ['25'] },
      { name: 'تشيكن برجر', prices: ['25'] },
      { name: 'تشيكن تشيز برجر', prices: ['30'] },
      { name: 'اسبيشيال برجر', prices: ['35'] },
      { name: 'تشيكن تكساس', prices: ['55'] },
      { name: 'تشيكن بسنت', prices: ['50'] },
      { name: 'تشيكن دبل بسنت', prices: ['80'] },
      { name: 'تشيكن دبل تكساس', prices: ['80'] },
      { name: 'هامر (مزيج لحمة + صوص)', prices: ['60'], isPopular: true },
      { name: 'دجاج بانية', prices: ['25'] },
      { name: 'دجاج كرسبي حار', prices: ['25'], isSpicy: true },
      { name: 'كفتة مشوية', prices: ['25'] },
      { name: 'كبدة إسكندراني', prices: ['25'] },
      { name: 'هوت دوج (سوسيس)', prices: ['25'] },
      { name: 'زنجر سوبريم', prices: ['65'], isSpicy: true },
      { name: 'f16', prices: ['65'] },
      { name: '122', prices: ['65'], isPopular: true },
      { name: 'ايطاليانو', prices: ['65'] },
      { name: 'شيش طاووق', prices: ['60'] },
      { name: 'فاهيتا ميكسيكانو', prices: ['70'] },
      { name: 'جمبري', prices: ['60'] },
      { name: 'سوبر فياجرة', prices: ['70'] },
      { name: 'تشيكن ماجنم', prices: ['60'] },
      { name: 'سوبر كرانش', prices: ['50'] },
      { name: 'شاورمة فراخ', prices: ['40'] },
      { name: 'شاورمة لحمة', prices: ['40'] },
    ]
  },
  {
    id: 'syrian',
    title: 'السورى New x New',
    emoji: '🌯',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?q=60&w=800',
    items: [
      { name: 'بطاطس', prices: ['25'] },
      { name: 'كفتة مشوية', prices: ['40'] },
      { name: 'كبدة إسكندراني', prices: ['40'] },
      { name: 'بانية كرسبي حار', prices: ['40'], isSpicy: true },
      { name: 'زنجر سوبريم', prices: ['60'], isSpicy: true },
      { name: 'شاورمة فراخ', prices: ['60'], isPopular: true },
      { name: 'شاورمة لحمة', prices: ['60'] },
    ]
  },
  {
    id: 'waffles',
    title: 'الوافل Waffle',
    emoji: '🧇',
    image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?q=60&w=800',
    items: [
      { name: 'إناناس', prices: ['50'] },
      { name: 'خوخ', prices: ['50'] },
      { name: 'شيكولاتة', prices: ['50'], isPopular: true },
      { name: 'كراميل', prices: ['50'] },
      { name: 'وايت', prices: ['50'] },
      { name: 'نص شيكولاتة + نص وايت', prices: ['60'] },
      { name: 'فواكة', prices: ['60'] },
      { name: 'ميكسات', prices: ['60'], isPopular: true },
      { name: 'مانجو', prices: ['60'] },
      { name: 'اوريو', prices: ['60'] },
      { name: 'موز', prices: ['60'] },
      { name: 'بستاشيو', prices: ['70'], isPopular: true },
      { name: 'طاجن باوند كيك', prices: ['60'] },
    ]
  },
  {
    id: 'appetizers',
    title: 'المقبلات',
    emoji: '🍟',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=60&w=800',
    items: [
      { name: 'سلطة كلوسلو', prices: ['10'] },
      { name: 'مياه', prices: ['6'] },
      { name: 'بوم فريت', prices: ['20'] },
      { name: 'بطاطس فرسكاس', prices: ['30'] },
      { name: 'كانز', prices: ['15'] },
    ]
  }
];

export const ADDITIONS_DATA = {
  image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=60&w=800',
  general: [
    { name: 'اللحوم', price: '25' },
    { name: 'مشروم', price: '25' },
    { name: 'جبنة', price: '25' },
    { name: 'بانية', price: '25' },
    { name: 'رانش', price: '15' },
    { name: 'صوص', price: '15' },
    { name: 'باربيكيو', price: '15' },
    { name: 'فاير', price: '15' },
  ],
  protein: {
    price: 'مجاني',
    items: ['خدمة التوصيل متوفرة لجميع المناطق']
  }
};
